### ISSUE TITLE
Sword Crashes the game

### ISSUE THREAD

**Issue by gamesruleyears** [vampire-studios/Randomly-Adding-Anything-Materials#12]
Since it is all randomly generated, I don't know if it is possible to fix this. I got a material that spawns in grass blocks. I was able to break it with my fist, and when I tried to make anything with it, all it could make was a sword. I attacked with the sword, and it appears to hit just fine and strike lightening, bu then the game freezes and crashes instantly.

I did have 2 other mods installed, but I don't think REI and HWYLA affect gameplay.

I am using Windows 10.

the contents of Config/raa_core.json
{
  "namingLanguage": "minecraft:en"
}

The folder:
[raa_materials.zip](https://github.com/vampire-studios/Randomly-Adding-Anything-Materials/files/4949166/raa_materials.zip)

The Json files:
[raacoreandmaterialsjsonfiles.zip](https://github.com/vampire-studios/Randomly-Adding-Anything-Materials/files/4949172/raacoreandmaterialsjsonfiles.zip)

Minecraft Log:

[13:09:16] [main/INFO]: Loading for game Minecraft 1.16.1
[13:09:19] [main/WARN]: Warnings were found! 
 - Conflicting versions found for fabric-api-base: used 0.1.3+12a8474c7c, also found 0.1.3+12a8474c02
[13:09:19] [main/INFO]: [FabricLoader] Loading 51 mods: fabric-renderer-api-v1@0.2.13+eae12eb802, fabric-keybindings-v0@0.2.0+3fa9f7c502, fabricloader@0.8.8+build.202, artifice@0.8.0+1.16-rc1, fabric-containers-v0@0.1.8+045df74f02, fabric-object-builder-api-v1@1.5.5+e00ecb5f02, fabric-dimensions-v1@1.0.0+a71b305302, raa_materials@0.1.3, fabric-api-base@0.1.3+12a8474c7c, fabric-rendering-data-attachment-v1@0.1.3+b7f9825d02, fabric-textures-v0@1.0.4+eae12eb802, fabric-rendering-fluids-v1@0.1.8+b7084faa02, waila@1.9.22, fabric-blockrenderlayer-v1@1.1.4+c6a8ea8902, fabric-lifecycle-events-v1@1.0.0+b0993bc102, vampirelib@1.8.0+build.1-1.16.1, fabric-renderer-registries-v1@2.0.1+5a0f9a6002, fabric-loot-tables-v1@0.1.10+059ea86602, fabric@0.14.0+build.371-1.16, fabric-particles-v1@0.2.1+0a6f2a7002, fabric-networking-v0@0.1.10+e00ecb5f02, minecraft@1.16.1, fabric-screen-handler-api-v1@1.0.1+f362c86e02, fabric-networking-blockentity-v0@0.2.5+b50ffc7b02, cloth-basic-math@0.5.1, fabric-command-api-v1@1.0.8+5ce5339802, jankson@2.0.1+j1.2.0, fabric-tool-attribute-api-v1@1.1.4+5794386e02, fabric-renderer-indigo@0.3.2+4d66bed502, cloth-client-events-v0@1.0.4, fabric-biomes-v1@0.2.7+059ea86602, roughlyenoughitems@4.5.5, fabric-item-api-v1@1.0.0+16acbe5b02, fabric-events-interaction-v0@0.3.3+7066030f02, fabric-crash-report-info-v1@0.1.2+b7f9825d02, fabric-rendering-v0@1.1.0+5341049002, fabric-rendering-v1@1.1.2+346247d702, fabric-key-binding-api-v1@1.0.0+e16a977402, raa_core@0.1.7+1.16.1, cloth-config2@4.5.6, autoconfig1u@3.2.0-unstable, fabric-resource-loader-v0@0.2.5+059ea86602, fabric-content-registries-v0@0.1.9+059ea86602, fabric-tag-extensions-v0@0.2.7+a4c57d8e02, fabric-registry-sync-v0@0.3.8+7dba2d6c02, fabric-commands-v0@0.2.0+52d3083602, fabric-mining-levels-v0@0.1.2+b764ce9902, fabric-events-lifecycle-v0@0.2.0+16acbe5b02, fabric-models-v0@0.1.0+dfdb52d602, fabric-item-groups-v0@0.2.0+438f963602, fabric-object-builders-v0@0.6.0+da175ad602
[13:09:19] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8 Source=file:/C:/Users/me/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.8+build.18/sponge-mixin-0.8+build.18.jar Service=Knot/Fabric Env=CLIENT
[13:09:19] [main/WARN]: Reference map 'raa-materials-refmap.json' for raa_materials.mixins.json could not be read. If this is a development environment you can ignore this message
[13:09:26] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', name='PROD'
[13:09:26] [main/INFO]: Setting user: Slenderman5
[13:09:27] [main/INFO]: Discovered plugin waila:core provided by waila at mcp.mobius.waila.addons.core.PluginCore
[13:09:27] [main/INFO]: Discovered plugin waila:vanilla provided by waila at mcp.mobius.waila.addons.minecraft.PluginMinecraft
[13:09:27] [main/INFO]: Registering plugin at mcp.mobius.waila.addons.core.PluginCore
[13:09:27] [main/INFO]: Registering plugin at mcp.mobius.waila.addons.minecraft.PluginMinecraft
[13:09:27] [main/INFO]: You are running VampireLib v1.8.0+build.1-1.16-pre2
[13:09:27] [main/INFO]: Initializing RAA: Core v0.1.0
[13:09:27] [main/INFO]: RAA Addon discovery: Starting
[13:09:27] [main/INFO]: Discovered addon : raa_materials
[13:09:27] [main/INFO]: RAA Addon discovery: Done
[13:09:27] [main/INFO]: RAA Addon discovered: 1
[13:09:27] [main/INFO]: Loaded RAA data file "C:\Users\me\AppData\Roaming\.minecraft\config\raa_materials\targets\ore_target_config.json".
[13:09:27] [main/INFO]: Loaded RAA data file "C:\Users\me\AppData\Roaming\.minecraft\config\raa_materials\materials\material_config.json".
[13:09:28] [main/INFO]: [Indigo] Registering Indigo renderer!
[13:09:28] [main/INFO]: Config loaded.
[13:09:29] [main/INFO]: Initializing RAA: Core Client v0.1.0
[13:09:29] [main/INFO]: RAA Client Addon discovery: Starting
[13:09:29] [main/INFO]: Discovered Client Addon : raa_materials
[13:09:29] [main/INFO]: RAA Client Addon discovery: Done
[13:09:29] [main/INFO]: RAA Client Addon discovered: 1
[13:09:29] [main/INFO]: Backend library: LWJGL version 3.2.2 build 10
[13:09:37] [main/INFO]: Narrator library for x64 successfully loaded
[13:09:37] [main/INFO]: Reloading ResourceManager: Default, Fabric Renderer API (v1), Fabric Key Bindings (v0), Artifice, Fabric Containers (v0), Fabric Object Builder API (v1), RAA: Materials, Fabric API Base, Fabric Rendering Data Attachment (v1), Fabric Textures (v0), Fabric Rendering Fluids (v1), Hwyla, Fabric BlockRenderLayer Registration (v1), Fabric Lifecycle Events (v1), VampireLib, Fabric Renderer Registries (v1), Fabric Loot Tables (v1), Fabric API, Fabric Networking (v0), Fabric Screen Handler API (v1), Fabric Networking Block Entity (v0), Jankson, Fabric Tool Attribute API (v1), Fabric Renderer - Indigo, Fabric Biomes (v1), Roughly Enough Items, Fabric Item API (v1), Fabric Events Interaction (v0), Fabric Crash Report Info (v1), Fabric Rendering (v0), Fabric Rendering (v1), Fabric Key Binding API (v1), RAA: Core, Cloth Config v4, Auto Config v1 Updated, Fabric Resource Loader (v0), Fabric Content Registries (v0), Fabric Tag Extensions (v0), Fabric Registry Sync (v0), Fabric Mining Levels (v0), Fabric Events Lifecycle (v0), Fabric Models (v0), Fabric Item Groups (v0), Fabric Object Builders (v0), raa_materials:pack
[13:09:48] [main/INFO]: OpenAL initialized.
[13:09:48] [main/INFO]: Sound engine started
[13:09:48] [main/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/blocks.png-atlas
[13:09:49] [main/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[13:09:49] [main/INFO]: Created: 1024x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[13:09:49] [main/INFO]: Created: 1024x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[13:09:49] [main/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[13:09:49] [main/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[13:09:49] [main/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[13:09:49] [main/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[13:09:49] [main/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[13:09:49] [main/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[13:11:19] [main/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[13:11:19] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[13:11:19] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[13:11:19] [main/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[13:11:19] [main/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[13:11:19] [main/INFO]: Reloading ResourceManager: Default, Fabric Renderer API (v1), Fabric Key Bindings (v0), Artifice, Fabric Containers (v0), Fabric Object Builder API (v1), RAA: Materials, Fabric API Base, Fabric Rendering Data Attachment (v1), Fabric Textures (v0), Fabric Rendering Fluids (v1), Hwyla, Fabric BlockRenderLayer Registration (v1), Fabric Lifecycle Events (v1), VampireLib, Fabric Renderer Registries (v1), Fabric Loot Tables (v1), Fabric API, Fabric Networking (v0), Fabric Screen Handler API (v1), Fabric Networking Block Entity (v0), Jankson, Fabric Tool Attribute API (v1), Fabric Renderer - Indigo, Fabric Biomes (v1), Roughly Enough Items, Fabric Item API (v1), Fabric Events Interaction (v0), Fabric Crash Report Info (v1), Fabric Rendering (v0), Fabric Rendering (v1), Fabric Key Binding API (v1), RAA: Core, Cloth Config v4, Auto Config v1 Updated, Fabric Resource Loader (v0), Fabric Content Registries (v0), Fabric Tag Extensions (v0), Fabric Registry Sync (v0), Fabric Mining Levels (v0), Fabric Events Lifecycle (v0), Fabric Models (v0), Fabric Item Groups (v0), Fabric Object Builders (v0), VampireLib, Fabric Tool Attribute API (v1), raa_materials:recipe_pack_1
[13:11:20] [main/INFO]: Loaded 7 recipes
[13:11:21] [main/INFO]: Loaded 927 advancements
[13:11:21] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', name='PROD'
[13:11:21] [Server thread/INFO]: Starting integrated minecraft server version 1.16.1
[13:11:21] [Server thread/INFO]: Generating keypair
[13:11:21] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[13:11:22] [main/INFO]: Preparing spawn area: 0%
[13:11:22] [main/INFO]: Preparing spawn area: 0%
[13:11:22] [main/INFO]: Preparing spawn area: 0%
[13:11:25] [main/INFO]: Preparing spawn area: 83%
[13:11:25] [main/INFO]: Preparing spawn area: 83%
[13:11:25] [main/INFO]: Preparing spawn area: 83%
[13:11:25] [main/INFO]: Preparing spawn area: 83%
[13:11:25] [main/INFO]: Preparing spawn area: 88%
[13:11:25] [main/INFO]: Preparing spawn area: 88%
[13:11:26] [main/INFO]: Preparing spawn area: 88%
[13:11:26] [main/INFO]: Preparing spawn area: 91%
[13:11:27] [main/INFO]: Preparing spawn area: 94%
[13:11:27] [main/INFO]: Preparing spawn area: 99%
[13:11:27] [main/INFO]: Time elapsed: 6066 ms
[13:11:28] [Server thread/INFO]: Changing view distance to 7, from 10
[13:11:29] [Server thread/INFO]: Slenderman5[local:E:913dbd47] logged in with entity id 131 at (-337.8608451437743, 65.0, -336.63917798963655)
[13:11:29] [Server thread/INFO]: Slenderman5 joined the game
[13:11:29] [Server thread/INFO]: Saving and pausing game...
[13:11:29] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Randomly Generated Blocks]'/minecraft:overworld
[13:11:32] [REI-SyncRecipes/INFO]: Reloading REI, registered 2 plugins: roughlyenoughitems:default_auto_crafting_plugin, roughlyenoughitems:default_plugin
[13:11:32] [main/INFO]: Loaded 112 advancements
[13:11:32] [REI-SyncRecipes/INFO]: Applied Check Tags for potion in 2ms.
[13:11:32] [REI-SyncRecipes/INFO]: Refiltered 0 entries in 36ms.
[13:11:32] [REI-SyncRecipes/INFO]: Reloaded 1661 stack entries, 1668 recipes displays, 3 exclusion zones suppliers, 5 overlay deciders, 1 visibility handlers and 13 categories (Crafting, Smelting, Smoking, Blasting, Campfire, Stone Cutting, Fuel, Brewing, Composting, Stripping, Smithing, Beacon Base, Information) in 2471ms.
[13:11:32] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Randomly Generated Blocks]'/minecraft:the_nether
[13:11:32] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Randomly Generated Blocks]'/minecraft:the_end
[13:11:32] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 3123ms or 62 ticks behind
[13:11:36] [main/INFO]: Using default channel type
[13:11:36] [main/INFO]: Started serving on 62925
[13:11:36] [main/INFO]: [CHAT] Local game hosted on port 62925
[13:11:41] [Server thread/INFO]: [Slenderman5: Set own game mode to Creative Mode]
[13:11:41] [main/INFO]: [CHAT] Set own game mode to Creative Mode
[13:12:10] [main/INFO]: Loaded 124 advancements
[13:13:34] [Server thread/FATAL]: Error executing task on Server
java.lang.NullPointerException: null
	at net.minecraft.class_1309.method_6020(class_1309.java:935) ~[intermediary-fabric-loader-0.8.8+build.202-1.16.1.jar:?]
	at net.minecraft.class_1309.method_6092(class_1309.java:877) ~[intermediary-fabric-loader-0.8.8+build.202-1.16.1.jar:?]
	at io.github.vampirestudios.raa_materials.effects.ItemEffectHandler.statusEffectForTarget(ItemEffectHandler.java:27) ~[raa-materials-0.1.3.jar:?]
	at io.github.vampirestudios.raa_materials.effects.MaterialEffects$$Lambda$2189/1530086509.apply(Unknown Source) ~[?:?]
	at io.github.vampirestudios.raa_materials.effects.MaterialEffects.apply(MaterialEffects.java:58) ~[raa-materials-0.1.3.jar:?]
	at io.github.vampirestudios.raa_materials.items.material.RAASwordItem.method_7873(RAASwordItem.java:41) ~[raa-materials-0.1.3.jar:?]
	at net.minecraft.class_1799.method_7979(class_1799.java:332) ~[intermediary-fabric-loader-0.8.8+build.202-1.16.1.jar:?]
	at net.minecraft.class_1657.method_7324(class_1657.java:1298) ~[intermediary-fabric-loader-0.8.8+build.202-1.16.1.jar:?]
	at net.minecraft.class_3222.method_7324(class_3222.java:1387) ~[intermediary-fabric-loader-0.8.8+build.202-1.16.1.jar:?]
	at net.minecraft.class_3244.method_12062(class_3244.java:1235) ~[intermediary-fabric-loader-0.8.8+build.202-1.16.1.jar:?]
	at net.minecraft.class_2824.method_12251(class_2824.java:74) ~[intermediary-fabric-loader-0.8.8+build.202-1.16.1.jar:?]
	at net.minecraft.class_2824.method_11054(class_2824.java:13) ~[intermediary-fabric-loader-0.8.8+build.202-1.16.1.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-fabric-loader-0.8.8+build.202-1.16.1.jar:?]
	at net.minecraft.class_2600$$Lambda$4976/2065403499.run(Unknown Source) ~[?:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-fabric-loader-0.8.8+build.202-1.16.1.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:144) [intermediary-fabric-loader-0.8.8+build.202-1.16.1.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [intermediary-fabric-loader-0.8.8+build.202-1.16.1.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:763) [intermediary-fabric-loader-0.8.8+build.202-1.16.1.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:154) [intermediary-fabric-loader-0.8.8+build.202-1.16.1.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:118) [intermediary-fabric-loader-0.8.8+build.202-1.16.1.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:745) [intermediary-fabric-loader-0.8.8+build.202-1.16.1.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:739) [intermediary-fabric-loader-0.8.8+build.202-1.16.1.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:127) [intermediary-fabric-loader-0.8.8+build.202-1.16.1.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:724) [intermediary-fabric-loader-0.8.8+build.202-1.16.1.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676) [intermediary-fabric-loader-0.8.8+build.202-1.16.1.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:256) [intermediary-fabric-loader-0.8.8+build.202-1.16.1.jar:?]
	at net.minecraft.server.MinecraftServer$$Lambda$4392/1551908548.run(Unknown Source) [intermediary-fabric-loader-0.8.8+build.202-1.16.1.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
[13:13:34] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.class_148: Ticking entity
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:877) ~[intermediary-fabric-loader-0.8.8+build.202-1.16.1.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:813) ~[intermediary-fabric-loader-0.8.8+build.202-1.16.1.jar:?]
	at net.minecraft.class_1132.method_3748(class_1132.java:93) ~[intermediary-fabric-loader-0.8.8+build.202-1.16.1.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:672) [intermediary-fabric-loader-0.8.8+build.202-1.16.1.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:256) [intermediary-fabric-loader-0.8.8+build.202-1.16.1.jar:?]
	at net.minecraft.server.MinecraftServer$$Lambda$4392/1551908548.run(Unknown Source) [intermediary-fabric-loader-0.8.8+build.202-1.16.1.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.NullPointerException
	at net.minecraft.class_1293.method_5585(class_1293.java:147) ~[intermediary-fabric-loader-0.8.8+build.202-1.16.1.jar:?]
	at net.minecraft.class_1309.method_6050(class_1309.java:725) ~[intermediary-fabric-loader-0.8.8+build.202-1.16.1.jar:?]
	at net.minecraft.class_1309.method_5670(class_1309.java:410) ~[intermediary-fabric-loader-0.8.8+build.202-1.16.1.jar:?]
	at net.minecraft.class_1308.method_5670(class_1308.java:271) ~[intermediary-fabric-loader-0.8.8+build.202-1.16.1.jar:?]
	at net.minecraft.class_1297.method_5773(class_1297.java:422) ~[intermediary-fabric-loader-0.8.8+build.202-1.16.1.jar:?]
	at net.minecraft.class_1309.method_5773(class_1309.java:2206) ~[intermediary-fabric-loader-0.8.8+build.202-1.16.1.jar:?]
	at net.minecraft.class_1308.method_5773(class_1308.java:338) ~[intermediary-fabric-loader-0.8.8+build.202-1.16.1.jar:?]
	at net.minecraft.class_1420.method_5773(class_1420.java:117) ~[intermediary-fabric-loader-0.8.8+build.202-1.16.1.jar:?]
	at net.minecraft.class_3218.method_18762(class_3218.java:615) ~[intermediary-fabric-loader-0.8.8+build.202-1.16.1.jar:?]
	at net.minecraft.class_3218$$Lambda$4736/122292287.accept(Unknown Source) ~[?:?]
	at net.minecraft.class_1937.method_18472(class_1937.java:603) ~[intermediary-fabric-loader-0.8.8+build.202-1.16.1.jar:?]
	at net.minecraft.class_3218.method_18765(class_3218.java:405) ~[intermediary-fabric-loader-0.8.8+build.202-1.16.1.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:873) ~[intermediary-fabric-loader-0.8.8+build.202-1.16.1.jar:?]
	... 6 more
[13:13:34] [Server thread/ERROR]: This crash report has been saved to: C:\Users\me\AppData\Roaming\.minecraft\crash-reports\crash-2020-07-20_13.13.34-server.txt
[13:13:34] [Server thread/INFO]: Stopping server
[13:13:34] [Server thread/INFO]: Saving players

**Comment by arthurbambou** [comment]
what was the name of the material?

**Comment by gamesruleyears** [comment]
@arthurbambou 
It is called Infraenum

**Comment by James-Banter** [comment]
me too

---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 7/23/20 6:42 PM
Description: Unexpected error

java.lang.ClassCastException: com.swordglowsblue.artifice.api.virtualpack.ArtificeResourcePackContainer cannot be cast to net.minecraft.class_1075
	at net.minecraft.class_310.method_5495(class_310.java:2256)
	at net.minecraft.class_1276.method_5485(class_1276.java:101)
	at net.minecraft.class_310.method_1523(class_310.java:1080)
	at net.minecraft.class_310.method_1514(class_310.java:654)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at link.infra.jumploader.Jumploader.onLoad(Jumploader.java:157)
	at cpw.mods.modlauncher.TransformationServiceDecorator.onLoad(TransformationServiceDecorator.java:53)
	at cpw.mods.modlauncher.TransformationServicesHandler.lambda$loadTransformationServices$11(TransformationServicesHandler.java:131)
	at cpw.mods.modlauncher.TransformationServicesHandler$$Lambda$51/842741472.accept(Unknown Source)
	at java.util.HashMap$Values.forEach(HashMap.java:972)
	at cpw.mods.modlauncher.TransformationServicesHandler.loadTransformationServices(TransformationServicesHandler.java:131)
	at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:56)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:75)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.16.1
	Minecraft Version ID: 1.16.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 663626352 bytes (632 MB) / 1521483776 bytes (1451 MB) up to 3008888832 bytes (2869 MB)
	CPUs: 16
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx3228m -Xms256m -XX:PermSize=256m
	Fabric Mods: 
		artifice: Artifice 0.12.0+20w29a
		autoconfig1u: Auto Config v1 Updated 3.2.0-unstable
		blue_endless_jankson: jankson +
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.0.4
		cloth-config2: Cloth Config v4 4.6.0
		diggusmaximus: Diggus Maximus 1.3.0-1.16
		fabric: Fabric API 0.15.1+build.380-1.16.1
		fabric-api-base: Fabric API Base 0.1.3+12a8474c7c
		fabric-biomes-v1: Fabric Biomes (v1) 0.2.7+059ea86602
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea8902
		fabric-command-api-v1: Fabric Command API (v1) 1.0.8+5ce5339802
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d3083602
		fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f02
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea86602
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d02
		fabric-dimensions-v1: fabric-dimensions-v1 1.0.0+a71b305302
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.3.3+7066030f02
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b02
		fabric-item-api-v1: Fabric Item API (v1) 1.0.0+16acbe5b02
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+438f963602
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+f404f3be02
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c502
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.1.0+013e49d202
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.0+386eb69e02
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce9902
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d602
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b02
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f02
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.5.6+a2d21ddd02
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.6.1+a2d21ddd02
		fabric-particles-v1: fabric-particles-v1 0.2.1+0a6f2a7002
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.3.8+7dba2d6c02
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.13+eae12eb802
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.3.3+0a55f37902
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.0.1+5a0f9a6002
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d02
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.8+b7084faa02
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+5341049002
		fabric-rendering-v1: Fabric Rendering (v1) 1.1.2+346247d702
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.2.6+f41e209802
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+97324d1102
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.2.7+a4c57d8e02
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+eae12eb802
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.1.4+5794386e02
		fabricloader: Fabric Loader 0.9.0+build.204
		jankson: Jankson 2.0.1+j1.2.0
		jumploader: Jumploader 1.0.12
		kyrptconfig: Kytpt Config 1.1.0-1.16
		minecraft: Minecraft 1.16.1
		modmenu: Mod Menu 1.14.5+build.30
		raa_core: RAA: Core 0.1.9+20w29a
		raa_materials: RAA: Materials 0.1.3
		roughlyenoughitems: Roughly Enough Items 4.10.2
		vampirelib: VampireLib 1.8.0+build.1-1.16.1
	Launched Version: forge-32.0.75
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1060 3GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 432.00, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	CPU: 16x AMD Ryzen 7 2700X Eight-Core Processor

**Comment by oliviathevampire** [comment]
this should be fixed possibly next week
