### ISSUE TITLE
Error starting the game with this addon in 1.16

### ISSUE THREAD

**Issue by mattstat716** [vampire-studios/Randomly-Adding-Anything-Materials#13]
[16:48:31] [main/FATAL]: Unreported exception thrown!
java.lang.ClassCastException: com.swordglowsblue.artifice.api.virtualpack.ArtificeResourcePackContainer cannot be cast to net.minecraft.class_1075
	at net.minecraft.class_310.method_5495(class_310.java:2256) ~[intermediary-fabric-loader-0.9.0+build.204-1.16.1.jar:?]
	at net.minecraft.class_1276.method_5485(class_1276.java:101) ~[intermediary-fabric-loader-0.9.0+build.204-1.16.1.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1080) ~[intermediary-fabric-loader-0.9.0+build.204-1.16.1.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:654) [intermediary-fabric-loader-0.9.0+build.204-1.16.1.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:215) [intermediary-fabric-loader-0.9.0+build.204-1.16.1.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192) [fabric-loader-0.9.0+build.204.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140) [fabric-loader-0.9.0+build.204.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-0.9.0+build.204.jar:?]

**Comment by oliviathevampire** [comment]
use this one https://www.curseforge.com/minecraft/mc-mods/randomly-adding-anything/files/2998611
